name: icapps_torch_compat
description: Plugin to turn on / off the torch (or flash of the camera) on all supported versions of Android (4.1+) and iOS
version: 2.0.0
homepage: https://github.com/icapps/flutter_torch_compat

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.icapps.icapps_torch_compat
        pluginClass: TorchCompatPlugin
      ios:
        pluginClass: TorchCompatPlugin
